---
title: 'Synthesis: model B'
output:
  html_document:
    css: ~/GitHub/ialsa-2016-amsterdam/libs/css/sidebar.css
    highlight: tango
    keep_md: yes
    theme: flatly
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "600px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 100
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./manipulation/map/3-compute-expectancies.R") 
```
This report describes the 


Estimation results of **Model XXX**, specified by the following input:
```{r specify-model, echo=T, results='show', message=FALSE}
```

# Load environmet
<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE}
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE}
```


<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=F, results='show', message=FALSE}
```

# Load data
<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='hide', message=FALSE}
```

# Functions used
```{r define-support-functions, echo=T, results='show', message=FALSE}
```

```{r define-le-functions, echo=T, results='show', message=FALSE}
```

```{r assemble-covariate-levels, echo=T, results='show', message=FALSE}
```

```{r specify-elect-options, echo=T, results='show', message=FALSE}
```

```{r compute-life-expectancies, echo=T, results='show', message=FALSE}
```

```{r compute-life-expectancies, echo=T, results='show', message=FALSE}
```

# Results
## msm
```{r print-results-1-1, echo=F, results='show', message=FALSE}
```

## Conditions
```{r print-conditions, echo=F, results='show', message=FALSE}
ds_levels %>% print()
```

## elect
```{r print-results-1-2, echo=T, results='asis', message=FALSE}
```

# Session Info
```{r}
sessionInfo()

```


