---
title: 'Model B : Estimation Results'
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
  html_document:
    css: ~/GitHub/ialsa-2016-amsterdam/libs/css/sidebar.css
    highlight: tango
    keep_md: yes
    theme: flatly
    toc: yes
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 100
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./manipulation/map/2-estimate-model-b-modification-2.R") 
```



Estimation results of **Model B**, specified by the following input:
```{r specify-model, echo=T, results='show', message=FALSE}
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, results='hide', message=FALSE}
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, results='hide', message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=echoChunks, results='hide', message=FALSE}
```


<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='hide', message=FALSE}
```

<!-- Inspect the datasets.   -->
```{r inspect-data, echo=echoChunks, results='hide', message=FALSE}
```


```{r inspect-created-multistates, echo=echoChunks, results='hide', message=FALSE}
```


```{r remove-invalid-cases, echo=echoChunks, results='hide', message=FALSE}
```


```{r split-education, echo=echoChunks, results='hide', message=FALSE}
```


```{r describe-age-composition, echo=echoChunks, results='hide', message=FALSE, eval=T, out.width="900px", out.height="300px", eval=F}
```


```{r prepare-for-estimation, echo=echoChunks, results='hide', message=FALSE}
```



```{r define-estimation-function, echo=F, results='show', message=FALSE}
```


```{r define-support-functions, echo=F, results='show', message=FALSE}
```


```{r specify-model, echo=FALSE, results='hide', message=FALSE}
```


```{r specify-msm-options, echo=FALSE, results='hide', message=FALSE}
```

```{r estimate-msm-models, echo=F, results='hide', message=FALSE}
```

```{r assemble-msm-models, echo=F, results='hide', message=FALSE, eval=F}
```

<!-- ## `elect` options -->
```{r specify-elect-options, echo=F, results='hide', message=FALSE, eval=F}
```

```{r compute-life-expectancies, echo=F, results='hide', message=FALSE, eval=F}
```

# Model 1

## Specification

The model was fitted using the following specification of covariates:
```
# Forward transitions:
  "1-2"       = "age + male  + edu_low_med + edu_low_high"
  "2-3"       = "age + male  + edu_low_med + edu_low_high"
# Backward transitions:
  "2-1"       = "age"
# Death transitions: 
  "1-4"       = "age + male"
  "2-4"       = "age + male"
  "3-4"       = "age + male"
```


```{r results-1-1, echo=echoChunks, results='hide', message=FALSE, eval=T, warning = T, out.width = "900px"}
model <- readRDS(paste0(pathSaveFolder,'mB_mod2_1.rds'))
msm_summary(model)
```


```{r results-1-2, echo=echoChunks, results='hide', message=FALSE, eval=T}
msm_details(model)
```

## Intensities
```{r results-1-3, echo=echoChunks, results='show', message=FALSE, eval=T}
pmatrix.msm(model)
```

## Hazards
```{r results-1-4, echo=echoChunks, results='show', message=FALSE, eval=T}
hazard.msm(model)
```


# Model 2

## Specification

The model was fitted using the following specification of covariates:
```
# Forward transitions:
  "1-2"       = "age + male  + edu_low_med + edu_low_high"
  "2-3"       = "age + male  + edu_low_med + edu_low_high"
# Backward transitions:
  "2-1"       = "age"
# Death transitions: 
  "1-4"       = "age + male + edu_low_med + edu_low_high"
  "2-4"       = "age + male + edu_low_med + edu_low_high"
  "3-4"       = "age + male + edu_low_med + edu_low_high"
```


```{r results-2-1, echo=echoChunks, results='hide', message=FALSE, eval=T, warning = T, out.width = "900px"}
model <- readRDS(paste0(pathSaveFolder,'mB_mod2_2.rds'))
msm_summary(model)
```


```{r results-2-2, echo=echoChunks, results='hide', message=FALSE, eval=T}
msm_details(model)
```

## Intensities
```{r results-2-3, echo=echoChunks, results='show', message=FALSE, eval=T}
pmatrix.msm(model)
```

## Hazards
```{r results-2-4, echo=echoChunks, results='show', message=FALSE, eval=T}
hazard.msm(model)
```




# Session Info
```{r}
sessionInfo()

```



```{r print-model-results-1, echo=echoChunks, results='asis', message=FALSE, eval=F}
```

