---
title: "Life Expectancies"
output:
  html_document:
    css: ~/GitHub/ialsa-2016-amsterdam/libs/css/sidebar.css
    highlight: tango
    keep_md: yes
    theme: flatly
    toc: yes
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 100
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- TRUE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./manipulation/map/2-estimate-models.R") 
```


# Load environmet
<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE}
```


<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE}
```


<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=echoChunks, results='show', message=FALSE}
```

# Load data
<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Inspect the datasets.   -->
```{r inspect-data, echo=echoChunks, results='show', message=FALSE}
```

# Multistates
```{r inspect-created-multistates, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echoChunks, results='show', message=FALSE}
```

# Analysis ready data
```{r inspect-clean-data, echo=echoChunks, results='show', message=FALSE}
```

# Age diagnostic
```{r new, echo=TRUE, results='show', message=FALSE, eval=T, out.width="900px"}
```

# Estimate multistate models
```{r estimate-msm-1, echo=echoChunks, results='show', message=FALSE}
```

# Estimate Life Expectancies
```{r compute-LE-1, echo=echoChunks, results='show', message=FALSE}
```

# Model results

## age
### msm summary
```{r results-1-1, echo=echoChunks, results='show', message=FALSE, eval=T, warning = F}
```

### solution
```{r results-1-2, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### ELECT summary 
```{r results-1-3, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### plots
```{r results-1-4, echo=echoChunks, results='show', message=FALSE, eval=T, out.width="900px"}
```


## age_bl
### msm summary
```{r results-2-1, echo=echoChunks, results='show', message=FALSE, eval=T, warning = F}
```

### solution
```{r results-2-2, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### ELECT summary 
```{r results-2-3, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### plots
```{r results-2-4, echo=echoChunks, results='show', message=FALSE, eval=T, out.width="900px"}
```


## male
### msm summary
```{r results-3-1, echo=echoChunks, results='show', message=FALSE, eval=T, warning = F}
```

### solution
```{r results-3-2, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### ELECT summary 
```{r results-3-3, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### plots
```{r results-3-4, echo=echoChunks, results='show', message=FALSE, eval=T, out.width="900px"}
```

## edu
### msm summary
```{r results-4-1, echo=echoChunks, results='show', message=FALSE, eval=T, warning = F}
```

### solution
```{r results-4-2, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### ELECT summary 
```{r results-4-3, echo=echoChunks, results='show', message=FALSE, eval=T}
```

### plots
```{r results-4-4, echo=echoChunks, results='show', message=FALSE, eval=T, out.width="900px"}
```

# Session Info
```{r}
sessionInfo()

```



```{r print-model-results-1, echo=echoChunks, results='asis', message=FALSE, eval=F}
```

